# Generated by Django 5.1.6 on 2025-03-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="問題文")),
                ("answer", models.TextField(verbose_name="解答")),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, to="main.question", verbose_name="問題"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="stages",
            field=models.ManyToManyField(
                blank=True, to="main.stage", verbose_name="ステージ"
            ),
        ),
    ]
