# Generated by Django 5.1.6 on 2025-03-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_question_stage_customuser_stages"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_name",
            field=models.CharField(
                default="default_name", max_length=20, verbose_name="ステージ名"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stage",
            name="stage_name",
            field=models.CharField(
                default="default_name", max_length=20, verbose_name="ステージ名"
            ),
            preserve_default=False,
        ),
    ]
