# Generated by Django 5.1.6 on 2025-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_question_question_name_stage_stage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_name",
            field=models.CharField(max_length=20, verbose_name="問題名"),
        ),
    ]
