# Generated by Django 5.1.6 on 2025-03-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_question_question_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
