# Generated by Django 5.1.6 on 2025-03-04 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_question_completed_remove_stage_completed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userstageprogress",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="userstageprogress",
            name="user",
        ),
        migrations.AddField(
            model_name="question",
            name="completed_users",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="ユーザー"
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="completed_users",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="ユーザー"
            ),
        ),
        migrations.DeleteModel(
            name="UserQuestionProgress",
        ),
        migrations.DeleteModel(
            name="UserStageProgress",
        ),
    ]
