# Generated by Django 5.1.6 on 2025-03-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_userstageprogress_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="main.stage",
            ),
        ),
    ]
