# Generated by Django 5.1.6 on 2025-03-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_customuser_stages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stage",
            name="questions",
        ),
        migrations.AddField(
            model_name="question",
            name="stage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="main.stage",
            ),
        ),
    ]
