# Generated by Django 5.1.6 on 2025-03-06 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_stage_questions_question_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="main.stage",
            ),
            preserve_default=False,
        ),
    ]
