# Generated by Django 5.1.6 on 2025-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_question_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_number",
            field=models.IntegerField(default=1),
        ),
    ]
