# Generated by Django 5.1.6 on 2025-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_question_question_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="question_name",
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("simple_number", "単一数字"),
                    ("single_addition", "一桁の足し算"),
                ],
                default="simple_number",
                max_length=50,
                verbose_name="問題の種類",
            ),
        ),
    ]
